"""empty message

Revision ID: 96ea3376eaf2
Revises: 136cc2f84e09
Create Date: 2025-03-29 22:45:13.028529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96ea3376eaf2'
down_revision = '136cc2f84e09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user2_pkey'),
    sa.UniqueConstraint('email', name='user2_email_key'),
    sa.UniqueConstraint('username', name='user2_username_key')
    )
    # ### end Alembic commands ###
