"""empty message

Revision ID: f662aa694a4f
Revises: 96ea3376eaf2
Create Date: 2025-03-29 23:20:27.410916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f662aa694a4f'
down_revision = '96ea3376eaf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restored_asset_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.drop_column('restored_asset_count')

    # ### end Alembic commands ###
